tier_1_cities = ['Mumbai', 'Delhi', 'Bangalore', 'Chennai', 'Kolkata', 'Hyderabad', 'Pune']
tier_2_cities = [
    "Vijayawada", "Visakhapatnam", "Guntur", "Nellore",
    "Guwahati",
    "Gaya", "Muzaffarpur",
    "Bhilai", "Durg", "Bilaspur",
    "Rajkot", "Bhavnagar", "Jamnagar",
    "Panipat", "Hisar", "Karnal",
    "Shimla",
    "Dhanbad", "Bokaro",
    "Mysuru", "Mangaluru", "Hubballi-Dharwad",
    "Kochi", "Kozhikode", "Thrissur",
    "Gwalior", "Jabalpur", "Ujjain",
    "Nagpur", "Nashik", "Aurangabad",
    "Imphal",
    "Shillong",
    "Aizawl",
    "Kohima",
    "Rourkela", "Sambalpur", "Cuttack",
    "Ludhiana", "Amritsar", "Patiala",
    "Ajmer", "Bikaner", "Udaipur", "Alwar",
    "Coimbatore", "Madurai", "Salem", "Tiruchirappalli",
    "Agra", "Meerut", "Varanasi", "Bareilly",
    "Dehradun", "Haridwar",
    "Asansol", "Siliguri", "Durgapur",
    "Puducherry",
    "Jammu", "Srinagar",
    "Raipur"
]
